apiVersion: 1
datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    uid: P8E80F9AEF21F6940
    jsonData:
      derivedFields:
        - datasourceUid: P214B5B846CF3925F
          # permissive regex: quotes optional, allow hex and hyphens, case-insensitive
          matcherRegex: '"?traceId"?\s*[:=]\s*"?([0-9a-fA-F-]+)"?'
          name: traceId
          url: '$${__value.raw}'
          datasourceName: Tempo

  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    uid: P214B5B846CF3925F
    isDefault: false
    jsonData:
      tracesToLogs:
        datasourceUid: P8E80F9AEF21F6940
        mappedTags:
          - key: service.name
            value: service_name
        mappedTagsValue: true
        filterByTraceID: true
        filterBySpanID: true
        customQuery: false
        spanStartTimeShift: "-5m"
        spanEndTimeShift: "5m"
        query: '{trace_id="$traceID"}'
      nodeGraph:
        enabled: true

  - name: Prometheus
    type: prometheus
    access: proxy
    isDefault: true
    url: http://prometheus:9090
