apiVersion: v1
kind: ConfigMap
metadata:
  name: los-app-promtail-config
  namespace: observability-sandbox
data:
  config.yml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0
    clients:
      - url: http://loki:3100/loki/api/v1/push
    positions:
      filename: /tmp/positions.yaml
    scrape_configs:
      - job_name: los-app-logs
        static_configs:
          - targets:
              - localhost
            labels:
              job: los-app
              __path__: /var/log/pods/*/app.log
        pipeline_stages: []
        relabel_configs:
          - source_labels: ['__meta_kubernetes_pod_name']
            target_label: 'pod'
          - source_labels: ['__meta_kubernetes_namespace']
            target_label: 'namespace'
