apiVersion: v1
kind: Service
metadata:
  name: los-app
  namespace: observability-sandbox
  labels:
    app: los-app
    app.kubernetes.io/name: los-app
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
      targetPort: http
  selector:
    app: los-app
