apiVersion: v1
kind: Service
metadata:
  name: los-app
  namespace: observability-sandbox
  labels:
    app: los-app
spec:
  type: LoadBalancer
  selector:
    app: los-app
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
