apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: los-app
  namespace: observability-sandbox
  labels:
    app: los-app
    release: prom
spec:
  selector:
    matchLabels:
      app: los-app
  namespaceSelector:
    matchNames:
      - observability-sandbox
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 30s
      scrapeTimeout: 10s
      basicAuth:
        username:
          name: los-app-demo-credentials
          key: app-user
        password:
          name: los-app-demo-credentials
          key: app-password
