global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:
  - '/etc/prometheus/alert-rules.yml'

scrape_configs:
  - job_name: 'spring-app'
    static_configs:
      - targets: ['los-app:8080']
    metrics_path: /actuator/prometheus
